hello/urls.py
from django.urls import path
from . import views


app_name = "hello"
urlpatterns = [
    path("", views.index, name="index"),
    path("response", views.response, name="response")
]

helloworld/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("hello.urls"))
]

hello/models.py
from django.db import models

# Create your models here.

hello/views.py
from django import forms
from django.shortcuts import render
from django.http import HttpResponse

name = ""


class newHello(forms.Form):
    name = forms.CharField(label="Enter your name: ")

# Create your views here.


def index(request):
    return render(request, "hello/index.html", {
        "name": name,
        "form": newHello()
    })


def response(request):
    if request.method == "POST":
        form = newHello(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
    return render(request, "hello/response.html", {
        "name": name
    })

hello/templates/hello/index.html
{% extends "hello/layout.html" %} {% block body%}
<h1>Hello World!</h1>
<form action="{% url 'hello:response' %}" method="post">
  {% csrf_token %} {{ form }}
  <input type="submit" value="Submit" name="submit" />
</form>
{% endblock %}

hello/templates/hello/layout.html
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World</title>
  </head>
  <body>
    {% block body %} {% endblock%}
  </body>
</html>

hello/templates/hello/response.html
{% extends "hello/layout.html" %} {% block body%}
<h1>Hello World</h1>
<p>Hello {{ name }}</p>
<a href="{% url 'hello:index' %}">Back</a>
{% endblock %}